<!-- index/index.phtml -->

<?php
    $translate = Zend_Registry::get('Zend_Translate');
    
    $this->headStyle()->appendStyle('
		
	');
?>

<div class="container">
	<ul class="tabs pull-right">
		<li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'login'), null, true); ?>">Sign In</a></li>
	</ul>
</div> <!-- /nav -->

<div id="content" class="container">

	<div class="hero-unit">
		<h1>Welcome to the <span class="green">XDE</span> Test!</h1>
		<p>Vestibulum id ligula porta felis euismod semper. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>
		<p><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'create'), null, true); ?>" class="btn primary large">Sign Up &raquo;</a></p>
	</div>

	<div class="row">
		<div class="span5">
			<ul class="sidebar">
				<li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'about'), null, true); ?>">About &raquo;</a></li>
				<li><a href="<?php echo $this->url(array('controller' => 'forums', 'action' => 'index'), null, true); ?>">Forums &raquo;</a></li>
				<li><a href="<?php echo $this->url(array('controller' => 'help', 'action' => 'index'), null, true); ?>">Help &raquo;</a></li>
			</ul>
		</div>
		
		<div class="span11">
			<h2>Heading</h2>
			<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
			<p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
			<p><a class="btn" href="#">View details &raquo;</a></p>
		</div>
	</div>

	
	<footer>
		<ul class="foot">
			<li>Copyright &copy; 2012 Company. All rights reserved</li>
			<li><a href="#">Terms of Services</a></li>
			<li><a href="#">Privacy Policy</a></li>
		</p>
		
	</footer>
</div> <!-- /container -->

