<!-- index/login.phtml -->

<?php
    $translate = Zend_Registry::get('Zend_Translate');
    
    $this->headStyle()->appendStyle('
    ');
?>

<div class="page-header">
	<h1>Sign In</h1>
</div>

<?php
	if ($this->messages) {
		echo '<div class="alert-message error">';
		foreach ($this->messages as $message) {
			echo '<p>' . $translate->_($message) . '</p>';
		}
		echo '</div>';
	}

?>

<?php echo $this->form; ?>
	