<!-- index/reset.phtml -->

<?php
    $translate = Zend_Registry::get('Zend_Translate');
    
    $this->headStyle()->appendStyle('
        #view-content
        {
            width: 50%;
            float: left;
        }
	');
?>

<div id="view-content">
	<h2>Create your new password</h2>
	<br />
    <fieldset class="login">
		<?php if (isset($this->form)) echo $this->form; ?>
		
		<?php
			if ($this->errors) {
				echo '<br /><ul class="errors">';
				foreach ($this->errors as $error) {
					echo '<li>' . $translate->_($error) . '</li>';
				}
				echo '</ul>';
			}
		
			if ($this->messages) {
				echo '<br /><ul class="errors ok">';
				foreach ($this->messages as $message) {
					echo '<li>' . $translate->_($message) . '</li>';
				}
				echo '</ul>';
			}
			
			if ($this->changed) {
				echo '<br /><a href="' . $this->url(array(
				'controller'	=> 'index', 
				'action'		=> 'login',
			), null, true) . '">Sign in</a> with your new password';
			}
		?>
	</fieldset>
</div>
