<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php	echo $this->headTitle('xde - prelogin') . PHP_EOL;	?>
		<meta name="description" content="">
		<meta name="author" content="">
		<?php	echo $this->headMeta(). PHP_EOL;	?>
		
		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		
		<link href="/css/bootstrap.min.css" rel="stylesheet">
		<link href="/css/style.css" rel="stylesheet">
		<?php	echo $this->headLink(). PHP_EOL;	?>
		<style type="text/css" media="screen">
			body {
				padding-top:	60px;
			}
		</style>
		<?php	echo $this->headStyle() . PHP_EOL;	?>

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
		<?php	echo $this->headScript() . PHP_EOL;	?>
		
		<link rel="shortcut icon" href="images/favicon.ico">
		<link rel="apple-touch-icon" href="images/apple-touch-icon.png">
		<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
	</head>
	<body>
		<div class="topbar">
			<div class="fill">
				<div class="container">
					<a class="brand" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), null, true); ?>">XDE</a>
					
					<ul class="secondary-nav">
						<li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'login'), null, true); ?>">Sign In</a></li>
					</ul>
				</div>
			</div>
		</div> <!-- /topbar -->
		
		<div id="subnav" class="container">
			<ul class="tabs pull-right">
				<li class="active"><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), null, true); ?>">Home</a></li>
				<li><a href="#">About</a></li>
				<li><a href="#">Forums</a></li>
				<li><a href="#">Help</a></li>
			</ul>
		</div> <!-- /subnav -->
		
		<div id="content" class="container">
			<?php
				echo $this->layout()->content;
			?>
			
			<footer>
				<ul class="foot">
					<li>Copyright &copy; 2012 Company. All rights reserved</li>
					<li><a href="#">Terms of Services</a></li>
					<li><a href="#">Privacy Policy</a></li>
				</p>
				
			</footer>
		</div> <!-- /container -->
		
	</body>
</html>

