<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php	echo $this->headTitle('xde - simple') . PHP_EOL;	?>
		<meta name="description" content="">
		<meta name="author" content="">
		<?php	echo $this->headMeta(). PHP_EOL;	?>
		
		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		
		<link href="/css/bootstrap.min.css" rel="stylesheet">
		<link href="/css/style.css" rel="stylesheet">
		<?php	echo $this->headLink(). PHP_EOL;	?>
		<?php	echo $this->headStyle() . PHP_EOL;	?>
		
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
		<?php	echo $this->headScript() . PHP_EOL;	?>
		
		<link rel="shortcut icon" href="images/favicon.ico">
		<link rel="apple-touch-icon" href="images/apple-touch-icon.png">
		<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
	</head>
	<body>
		
		<?php
			echo $this->layout()->content;
		?>
		
	</body>
</html>

